### PR TITLE
fullscreen table

### PR DESCRIPTION
**Pull request by pugson**

### CODE REVIEW

**Comment by pugson** [comment]
ok this will work properly now

**Comment by pugson** [comment]
sorry for the formatting. no idea how to disable my global line length vscode config

**Comment by davidfurlong** [comment]
> sorry for the formatting. no idea how to disable my global line length vscode config

all good, next time it's cmd shift P -> save without formatting

**Comment by pugson** [comment]
yeah that's what i did but it still wrapped the lines differently

**Pull request closed without merging**
